#!/usr/bin/env python3
"""
Regenerate HTML evidence table rows from corrected reference_map.json
Updates index.html with accurate file paths and reference codes
"""
import json
import re
import sys
from datetime import datetime

def load_reference_map(filepath="reference_map.json"):
    """Load the reference map."""
    with open(filepath, "r", encoding="utf-8") as f:
        return json.load(f)

def generate_table_rows(refmap):
    """
    Generate HTML table rows in chronological order.
    Returns: list of (date_str, html_row) tuples for ordering
    """
    # Define entries in chronological order with their actual descriptions
    entries = [
        ("B1", "18 Mar 2025", "Admitted to Akeso Stepping Stones Clinic — severe depression and PTSD diagnosed"),
        ("SCR1", "23 Sep 2025", "\"Wilma\" gender-identity harassment — Microsoft Teams message constituting EEA Section 6 violation"),
        ("VICT1", "23 Oct 2025", "VICT1 — Protected disclosure: Gexus-DMS integration gap identified. Refused to contact a 75-year-old patient using demonstrably false data. Root Cause Analysis generated by Medscheme's own systems confirms structural design flaw."),
        ("E1", "31 Oct 2025", "Recorded admission of retaliatory intent: \"You made a case of harassment against me, so I can make a case of harassment against you.\""),
        ("GRC1", "9 Dec 2025", "GRC1 — Priority 1 Material Risk Report to Board of AfroCentric. 38 attachments. No Board response."),
        ("O1", "10 Dec 2025", "CCMA opposing affidavit filed — falsely states complainant is a \"Care Coordinator,\" attacks character, dismisses clinical depression as a \"cynical excuse.\" Potential perjury."),
        ("GRC2", "11 Dec 2025", "GRC2 — Urgent Board update: legal opposition confirms institutional bad faith"),
        ("H2", "12 Dec 2025", "Constructive dismissal — resignation citing LRA Section 186(1)(e). Employer subsequently files false UI-19 (Code 6: Resigned instead of Code 7: Constructive Dismissal)."),
        ("GRC3", "16 Dec 2025", "GRC3 — Maximum Severity GRC Escalation to Board Audit &amp; Risk Committee. Explicit warning: \"Failure to act will be considered a miscarriage of ethical justice and an approval of director-level psychological harm.\""),
        ("CRO1", "18 Dec 2025", "CRO suppression email — Monwabisi Kula: \"can I please ask you to stop sending these e-mails to our directors?\" Active suppression of a material risk report by the Chief Risk Officer."),
        ("U1", "23 Dec 2025", "Initial CMS complaint lodged with full evidentiary bundle"),
        ("U5", "4 Feb 2026", "CMS first declination — deflects to HPCSA. Jurisdictional error."),
        ("J2", "10 Feb 2026", "SAHRC acknowledges \"seriousness of the concerns\" — then goes silent. No own-initiative investigation."),
        ("U8", "2 Apr 2026", "Formal CMS re-engagement (CMS-REQUEST-3) — cites Discovery Health precedent. CMS exercises jurisdiction over Discovery Health for financial processing error in January 2026 but declines Medscheme/GEMS for clinical data integrity error."),
        ("M1", "16 Apr 2026", "Western Cape High Court grants ex parte interim interdict — answering affidavit concealed from court by Deneys Reitz. Gag order imposed. Fraud on the court."),
        ("U11", "7 May 2026", "CMS second declination — demands new complaint form after High Court interim order, exposing complainant to contempt of court. Contempt trap."),
    ]
    
    rows = []
    for ref, date, event in entries:
        if ref not in refmap:
            print(f"[WARNING] {ref} not in reference_map.json")
            continue
        
        file_path = refmap[ref]["file"]
        # Add "public/" prefix for onclick
        full_path = f"public/{file_path}" if not file_path.startswith("public/") else file_path
        
        html = f'                <tr><td>{date}</td><td>{event}</td><td><span class="evidence-link" onclick="showEvidenceModal(\'{full_path}\')" title="Open evidence">{ref}</span></td></tr>'
        rows.append(html)
    
    return "\n".join(rows)

def update_index_html(new_rows):
    """
    Find and replace the evidence table rows in index.html
    """
    # Read current index.html
    with open("index.html", "r", encoding="utf-8") as f:
        content = f.read()
    
    # Backup original
    with open("index.html.backup_before_regen", "w", encoding="utf-8") as f:
        f.write(content)
    print("✓ Backed up index.html to index.html.backup_before_regen")
    
    # Find the table section containing evidence rows
    # Pattern: from <!-- MASTER CHRONOLOGY --> to </table>
    pattern = r'(<!-- MASTER CHRONOLOGY -->.*?<tr><th>Date</th><th>Event</th><th>Evidence Ref</th></tr>)(.*?)(</table>)'
    
    def replacement(match):
        header = match.group(1)
        old_rows = match.group(2)
        footer = match.group(3)
        return header + "\n" + new_rows + "\n                " + footer
    
    updated_content = re.sub(pattern, replacement, content, flags=re.DOTALL)
    
    if updated_content == content:
        print("[ERROR] Could not find evidence table in index.html")
        return False
    
    # Write updated content
    with open("index.html", "w", encoding="utf-8") as f:
        f.write(updated_content)
    
    print("✓ Updated index.html with regenerated evidence table rows")
    return True

def verify_changes():
    """Verify the changes were applied correctly"""
    with open("index.html", "r", encoding="utf-8") as f:
        content = f.read()
    
    # Count evidence rows
    evidence_rows = len(re.findall(r'<span class="evidence-link"', content))
    print(f"✓ Verified: {evidence_rows} evidence-linked rows in index.html")
    
    # Check for specific refs
    refs_to_check = ["B1", "SCR1", "VICT1", "GRC1", "GRC2", "GRC3", "CRO1", "U1", "M1", "U11"]
    for ref in refs_to_check:
        if f'>{ref}</span>' in content:
            print(f"  ✓ {ref} found")
        else:
            print(f"  ✗ {ref} NOT FOUND")

def main():
    print("="*100)
    print("REGENERATING HTML EVIDENCE TABLE FROM reference_map.json")
    print("="*100)
    
    # Load reference map
    refmap = load_reference_map()
    print(f"✓ Loaded {len(refmap)} evidence codes from reference_map.json\n")
    
    # Generate new table rows
    new_rows = generate_table_rows(refmap)
    print(f"✓ Generated {len(new_rows.splitlines())} HTML table rows\n")
    
    # Update index.html
    if not update_index_html(new_rows):
        sys.exit(1)
    
    print()
    verify_changes()
    
    print("\n" + "="*100)
    print("NEXT STEPS:")
    print("="*100)
    print("1. Review index.html in your browser — check that all evidence links work")
    print("2. Verify on live Vercel deployment")
    print("3. Run: git add index.html reference_map.json && git commit -m 'Regenerate evidence table from corrected reference_map.json'")
    print("4. Run: git push origin main")
    print("="*100)

if __name__ == "__main__":
    main()
